version: "3.8"

volumes:
  kong_data: {}

networks:
  kong-net:


services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    restart: on-failure
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_USER: kong
    #   POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    #   POSTGRES_DB: kong
    env_file:
      - kong.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 30s
      timeout: 30s
      retries: 3

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: ${KONG_DOCKER_TAG:-kong:latest}
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    env_file:
      - kong.env
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: ${KONG_DOCKER_TAG:-kong:latest}
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    env_file:
      - kong.env
    depends_on:
      - kong-database
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-password}@kong-database:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:${KONG_PG_PASSWORD:-password}@kong-database:5432/konga
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

  #######################################
  # Login: The Login microservice
  #######################################

  login:
    image: spmg7t6/is212_login:rc-857f429eebbd1344340230d452fedea3d3e97600
    networks:
      - kong-net
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - db.env

  #######################################
  # Skill: The Skill microservice
  #######################################

  skill:
    image: spmg7t6/is212_skill:rc-9d414d668156dff7795f314785a44135b76e5d8d
    networks:
      - kong-net
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - db.env

  #######################################
  # Profile: The Profile microservice
  #######################################

  profile:
    image: spmg7t6/is212_profile:rc-857f429eebbd1344340230d452fedea3d3e97600
    networks:
      - kong-net
    ports:
      - "5002:5002"
    restart: always
    env_file:
      - db.env

  #######################################
  # Role: The Role microservice
  #######################################

  role:
    image: spmg7t6/is212_role:rc-857f429eebbd1344340230d452fedea3d3e97600
    networks:
      - kong-net
    ports:
      - "5003:5003"
    restart: always
    env_file:
      - db.env

  #######################################
  # Web: The Web App service
  #######################################

  web:
    image: spmg7t6/is212_web:rc-dd2fb6b9afd130edf2f92845a7daa7ebaffadb6d
    networks:
      - kong-net
    ports:
      - "80:80"
    restart: always
